import 'enums.dart';
import 'partner_preferences.dart';
import 'profile_photo.dart';

/// The matrimonial profile — built up field-by-field across the
/// onboarding flow (screens 05–16), so every field is nullable until
/// [ReviewConfirmScreen] submits it.
class Profile {
  final String id;

  /// Short, human-readable public ID (e.g. "VV351159") generated by the
  /// backend — this is what's shown to users and shared, not the raw [id]
  /// UUID, which is an internal database key.
  final String profileCode;

  final ProfileFor? profileFor;

  // Basic details
  final String? firstName;
  final String? lastName;
  final DateTime? dateOfBirth;
  final Gender? gender;
  final MaritalStatus? maritalStatus;
  final String? city;
  final String? state;
  final String? country;
  final String? religion;
  final String? motherTongue;

  // Community
  final String? community;
  final String? subCommunity;
  final bool? casteNoBar;

  // Education & profession
  final String? highestEducation;
  final String? college;
  final String? profession;
  final String? annualIncome;
  final String? workWith;
  final String? companyName;

  /// Opts the profile out of Vivah's affiliated matchmaking network.
  final bool? matchmakingOptOut;

  // Family
  final FamilyType? familyType;
  final FamilyValues? familyValues;
  final String? fatherOccupation;
  final String? motherOccupation;
  final int? brothers;
  final int? sisters;
  final bool? livesWithFamily;
  final String? familyFinancialStatus;

  final List<String> hobbies;
  final bool selfieVerified;

  // Astro
  final ManglikStatus? manglik;
  final String? rashi;
  final String? nakshatra;
  final String? birthTime;
  final String? birthPlace;

  // Physical
  final int? heightCm;
  final int? weightKg;
  final BodyType? bodyType;
  final String? complexion;
  final bool? hasDisability;

  // Lifestyle
  final DietType? diet;
  final HabitLevel? smoking;
  final HabitLevel? drinking;

  final String? aboutMe;
  final List<String> photoUrls;
  final String? profilePhotoUrl;

  /// Stored photos with their backend ids — empty for a draft that hasn't
  /// been saved yet (local picker paths in [photoUrls] have no id until
  /// they're uploaded). Needed to delete a photo or set the primary one.
  final List<ProfilePhoto> photos;

  final PartnerPreferences partnerPreferences;
  final VerificationStatus verificationStatus;
  final bool submitted;

  /// 'public' or 'private' — who can view this profile. Null means "not
  /// yet loaded / leave unchanged", not "unset" (the backend defaults new
  /// profiles to public).
  final String? visibility;

  /// When this profile was created on the backend — null for a draft
  /// that hasn't been submitted yet.
  final DateTime? createdAt;

  const Profile({
    this.id = '',
    this.profileCode = '',
    this.profileFor,
    this.firstName,
    this.lastName,
    this.dateOfBirth,
    this.gender,
    this.maritalStatus,
    this.city,
    this.state,
    this.country,
    this.religion,
    this.motherTongue,
    this.community,
    this.subCommunity,
    this.casteNoBar,
    this.highestEducation,
    this.college,
    this.profession,
    this.annualIncome,
    this.workWith,
    this.companyName,
    this.matchmakingOptOut,
    this.familyType,
    this.familyValues,
    this.fatherOccupation,
    this.motherOccupation,
    this.brothers,
    this.sisters,
    this.livesWithFamily,
    this.familyFinancialStatus,
    this.hobbies = const [],
    this.selfieVerified = false,
    this.manglik,
    this.rashi,
    this.nakshatra,
    this.birthTime,
    this.birthPlace,
    this.heightCm,
    this.weightKg,
    this.bodyType,
    this.complexion,
    this.hasDisability,
    this.diet,
    this.smoking,
    this.drinking,
    this.aboutMe,
    this.photoUrls = const [],
    this.photos = const [],
    this.profilePhotoUrl,
    this.partnerPreferences = const PartnerPreferences(),
    this.verificationStatus = VerificationStatus.unverified,
    this.submitted = false,
    this.visibility,
    this.createdAt,
  });

  String? get fullName {
    final parts = [firstName, lastName].where((p) => p != null && p.trim().isNotEmpty);
    return parts.isEmpty ? null : parts.join(' ');
  }

  int? get age {
    if (dateOfBirth == null) return null;
    final now = DateTime.now();
    var years = now.year - dateOfBirth!.year;
    if (now.month < dateOfBirth!.month ||
        (now.month == dateOfBirth!.month && now.day < dateOfBirth!.day)) {
      years--;
    }
    return years;
  }

  String get heightLabel {
    if (heightCm == null) return '—';
    final feet = (heightCm! / 30.48).floor();
    final inches = ((heightCm! / 2.54) % 12).round();
    return "$feet' $inches\" ($heightCm cm)";
  }

  Profile copyWith({
    String? id,
    String? profileCode,
    ProfileFor? profileFor,
    String? firstName,
    String? lastName,
    DateTime? dateOfBirth,
    Gender? gender,
    MaritalStatus? maritalStatus,
    String? city,
    String? state,
    String? country,
    String? religion,
    String? motherTongue,
    String? community,
    String? subCommunity,
    bool? casteNoBar,
    String? highestEducation,
    String? college,
    String? profession,
    String? annualIncome,
    String? workWith,
    String? companyName,
    bool? matchmakingOptOut,
    FamilyType? familyType,
    FamilyValues? familyValues,
    String? fatherOccupation,
    String? motherOccupation,
    int? brothers,
    int? sisters,
    bool? livesWithFamily,
    String? familyFinancialStatus,
    List<String>? hobbies,
    bool? selfieVerified,
    ManglikStatus? manglik,
    String? rashi,
    String? nakshatra,
    String? birthTime,
    String? birthPlace,
    int? heightCm,
    int? weightKg,
    BodyType? bodyType,
    String? complexion,
    bool? hasDisability,
    DietType? diet,
    HabitLevel? smoking,
    HabitLevel? drinking,
    String? aboutMe,
    List<String>? photoUrls,
    List<ProfilePhoto>? photos,
    String? profilePhotoUrl,
    PartnerPreferences? partnerPreferences,
    VerificationStatus? verificationStatus,
    bool? submitted,
    String? visibility,
    DateTime? createdAt,
    // Passing `null` to a copyWith parameter is indistinguishable from
    // omitting it, so clearing a field needs its own flag. Only the
    // cascading location/community fields have one, because they're the
    // only ones a later choice has to invalidate: change country and the
    // old state is not just stale but wrong.
    bool clearState = false,
    bool clearCity = false,
    bool clearCommunity = false,
    bool clearSubCommunity = false,
  }) {
    return Profile(
      id: id ?? this.id,
      profileCode: profileCode ?? this.profileCode,
      profileFor: profileFor ?? this.profileFor,
      firstName: firstName ?? this.firstName,
      lastName: lastName ?? this.lastName,
      dateOfBirth: dateOfBirth ?? this.dateOfBirth,
      gender: gender ?? this.gender,
      maritalStatus: maritalStatus ?? this.maritalStatus,
      city: clearCity ? null : (city ?? this.city),
      state: clearState ? null : (state ?? this.state),
      country: country ?? this.country,
      religion: religion ?? this.religion,
      motherTongue: motherTongue ?? this.motherTongue,
      community: clearCommunity ? null : (community ?? this.community),
      subCommunity: clearSubCommunity ? null : (subCommunity ?? this.subCommunity),
      casteNoBar: casteNoBar ?? this.casteNoBar,
      highestEducation: highestEducation ?? this.highestEducation,
      college: college ?? this.college,
      profession: profession ?? this.profession,
      annualIncome: annualIncome ?? this.annualIncome,
      workWith: workWith ?? this.workWith,
      companyName: companyName ?? this.companyName,
      matchmakingOptOut: matchmakingOptOut ?? this.matchmakingOptOut,
      familyType: familyType ?? this.familyType,
      familyValues: familyValues ?? this.familyValues,
      fatherOccupation: fatherOccupation ?? this.fatherOccupation,
      motherOccupation: motherOccupation ?? this.motherOccupation,
      brothers: brothers ?? this.brothers,
      sisters: sisters ?? this.sisters,
      livesWithFamily: livesWithFamily ?? this.livesWithFamily,
      familyFinancialStatus: familyFinancialStatus ?? this.familyFinancialStatus,
      hobbies: hobbies ?? this.hobbies,
      selfieVerified: selfieVerified ?? this.selfieVerified,
      manglik: manglik ?? this.manglik,
      rashi: rashi ?? this.rashi,
      nakshatra: nakshatra ?? this.nakshatra,
      birthTime: birthTime ?? this.birthTime,
      birthPlace: birthPlace ?? this.birthPlace,
      heightCm: heightCm ?? this.heightCm,
      weightKg: weightKg ?? this.weightKg,
      bodyType: bodyType ?? this.bodyType,
      complexion: complexion ?? this.complexion,
      hasDisability: hasDisability ?? this.hasDisability,
      diet: diet ?? this.diet,
      smoking: smoking ?? this.smoking,
      drinking: drinking ?? this.drinking,
      aboutMe: aboutMe ?? this.aboutMe,
      photoUrls: photoUrls ?? this.photoUrls,
      photos: photos ?? this.photos,
      profilePhotoUrl: profilePhotoUrl ?? this.profilePhotoUrl,
      partnerPreferences: partnerPreferences ?? this.partnerPreferences,
      verificationStatus: verificationStatus ?? this.verificationStatus,
      submitted: submitted ?? this.submitted,
      visibility: visibility ?? this.visibility,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
