package chatguard

import (
	"net/url"
	"regexp"
	"strings"
)

// url.go detects HTTP(S) URLs and bare-domain mentions ("meet me on
// example dot com/xyz"), and separates the app's own approved domains
// (deep links, invite/share links generated by the app itself) from
// external ones that should be blocked.

var (
	urlRe = regexp.MustCompile(`(?i)\b((?:https?://|www\.)[^\s]+|[a-z0-9\-]+\.(?:com|in|net|org|me|io|co|app|link|ly|gl|to|gg|cc|tv|xyz)(?:/[^\s]*)?|[a-z0-9\-]+\.[a-z]{2,6}/[^\s]+)\b`)

	// "domain dot com"-style spoken-out URLs.
	spokenDomainRe = regexp.MustCompile(`(?i)\b([a-z0-9\-]+)\s+dot\s+(com|in|net|org|me|io|co|app|link)\b`)
)

// detectExternalLink reports whether body contains a URL whose host is
// not in allowedDomains (the app's own domains — see chatguard.Config).
func detectExternalLink(body string, allowedDomains []string) bool {
	candidates := urlRe.FindAllString(body, -1)
	for _, m := range spokenDomainRe.FindAllString(body, -1) {
		candidates = append(candidates, m)
	}
	if len(candidates) == 0 {
		return false
	}
	for _, raw := range candidates {
		host := extractHost(raw)
		if host == "" {
			continue
		}
		if !isAllowedHost(host, allowedDomains) {
			return true
		}
	}
	return false
}

func extractHost(raw string) string {
	raw = strings.TrimRight(raw, ".,!?)]}\"'")
	if m := spokenDomainRe.FindStringSubmatch(raw); m != nil {
		return m[1] + "." + m[2]
	}
	candidate := raw
	if !strings.Contains(candidate, "://") {
		candidate = "http://" + candidate
	}
	u, err := url.Parse(candidate)
	if err != nil {
		return ""
	}
	return strings.ToLower(u.Hostname())
}

func isAllowedHost(host string, allowedDomains []string) bool {
	for _, allowed := range allowedDomains {
		allowed = strings.ToLower(strings.TrimSpace(allowed))
		if allowed == "" {
			continue
		}
		if host == allowed || strings.HasSuffix(host, "."+allowed) {
			return true
		}
	}
	return false
}
